# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyTrading' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyTrading
  pod 'GRDB.swift'
  pod 'AWSS3'

end
